image: node:latest

stages:
  - install
  - lint
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install-dependencies:
  stage: install
  script:
    - npm install

eslint:
  stage: lint
  script:
    - echo "Linting"
    - eslint --init
    - eslint src/*.js

build:
  stage: build
  script:
    - echo "Building"
    - mkdir build
    - touch build/info.txt

test:
  stage: test
  script:
    - echo "Testing"
    - test -f "build/info.txt"
