image: node:latest

stages:
  - install
  - build
  - lint
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install-dependencies:
  stage: install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm install

build:
  stage: build
  script:
    - npm run build

eslint:
  stage: lint
  cache:
    policy: pull
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - ls
    - eslint --init
    - eslint ./node_modules/bin/eslint.js

test:
  stage: test
  script:
    - npm run test
