image: node:latest

stages:
  - lint
  - build
  - test

eslint:
  stage: lint
  script:
    - echo "Linting"
    -
      npm install eslint \
      eslint-config-airbnb \
      eslint-plugin-react
    - eslint --init
    - node_modules/eslint/bin/eslint.js

build:
  stage: build
  script:
    - echo "Building"
    - mkdir build
    - touch build/info.txt
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - echo "Testing"
    - test -f "build/info.txt"
