image: node:latest

stages:
  - install
  - lint
  - build
  - test

install-all:
  stage: install
  script:
    - npm install

eslint:
  stage: lint
  script:
    - echo "Linting"
    - eslint --init
    - eslint src/*.js

build:
  stage: build
  script:
    - echo "Building"
    - mkdir build
    - touch build/info.txt
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - echo "Testing"
    - test -f "build/info.txt"
