stages:
  - lint
  - build
  - test

lint:
  stage: lint
  script:
    - echo "Linting"
    - npm i eslint
    - node_modules/eslint/bin/eslint.js

build:
  stage: build
  script:
    - echo "Building"
    - mkdir build
    - touch build/info.txt
  artifacts:
    paths:
      - build/

test:
  stage: test
  script:
    - echo "Testing"
    - test -f "build/info.txt"
