image: node:latest

stages:
  - install
  - lint
  - build
  - test

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

install-dependencies:
  stage: install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm install

eslint:
  stage: lint
  cache:
    policy: pull
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - eslint --init

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - npm run test
