image: node:latest

stages:
  - install
  - lint
  - build
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

install-dependencies:
  stage: install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm install

eslint:
  stage: lint
  script:
    - echo "Linting"
    - eslint --init
    - eslint src/*.js

build:
  stage: build
  script:
    - echo "Building"
    - npm run build

test:
  stage: test
  script:
    - echo "Testing"
    - npm run test
