image: node:latest

stages:
  - lint
  - build
  - test

eslint:
  stage: lint
  script:
    - npm install
    - npm run lint

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - npm run test
