image: node:latest

stages:
  - install
  - lint
  - build
  - test

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/

install-dependencies:
  stage: install
  script:
    - npm install

eslint:
  stage: lint
  script:
    - eslint --init
    - eslint src/*.js

build:
  stage: build
  script:
    - npm run build

test:
  stage: test
  script:
    - npm run test
